final List<Map<String, dynamic>> authorsData = [
    {
      'id': '1',
      'name': 'Rayford Eddings',
      'username': 'rayford_eddings',
      'profileImageUrl': 'https://img.freepik.com/free-psd/3d-render-avatar-character_23-2150611750.jpg?semt=ais_hybrid&w=740',
      'followers': 1250,
      'quizzes': 45,
      'isFollowing': false,
    },
    {
      'id': '2',
      'name': 'Willard Goode',
      'username': 'willard_goode',
      'profileImageUrl': 'https://img.freepik.com/free-psd/3d-rendering-avatar_23-2150833576.jpg',
      'followers': 890,
      'quizzes': 32,
      'isFollowing': false,
    },
    {
      'id': '3',
      'name': 'Hannah Nehls',
      'username': 'hannah_nehls',
      'profileImageUrl': 'https://img.freepik.com/premium-photo/3d-cartoon-avatar-man-minimal-3d-character-avatar-profile_652053-2068.jpg?w=360',
      'followers': 2100,
      'quizzes': 67,
      'isFollowing': false,
    },
    {
      'id': '4',
      'name': 'Geoffrey Dorrance',
      'username': 'geoffrey_dorrance',
      'profileImageUrl': 'https://media.istockphoto.com/id/1415055580/vector/3d-man-avatar-happy-smiling-face-icon-young-businessman-student-or-freelancer.jpg?s=612x612&w=0&k=20&c=FmAiiREZji9GV77yogJSLzWfk-COnX864FxKd5A7vtU=',
      'followers': 756,
      'quizzes': 28,
      'isFollowing': false,
    },
    {
      'id': '5',
      'name': 'Clinton Kervin',
      'username': 'clinton_kervin',
      'profileImageUrl': 'https://media.istockphoto.com/id/1458818449/vector/3d-man-icon-person-avatar-male-character-face-cartoon-business-glasses-vector-cheerful-boy.jpg?s=612x612&w=0&k=20&c=xRdAjy7284u5eMB_dA2zXIp2oQ8HlYNbEJ6ksC5Mr3Q=',
      'followers': 1800,
      'quizzes': 53,
      'isFollowing': false,
    },
    {
      'id': '6',
      'name': 'Lavern Laboy',
      'username': 'lavern_laboy',
      'profileImageUrl': 'https://media.istockphoto.com/id/1389823037/vector/young-smiling-woman-mia-avatar-3d-vector-people-character-illustration-cartoon-minimal-style.jpg?s=612x612&w=0&k=20&c=ciwsDqBIy3mcTxhWN4I1S-kKSTvjoN1einMrQawNZDQ=',
      'followers': 1800,
      'quizzes': 53,
      'isFollowing': false,
    },
    {
      'id': '7',
      'name': 'Aillen Fullbright',
      'username': 'aileen_fullbright',
      'profileImageUrl': 'https://media.istockphoto.com/id/1296058958/vector/happy-young-woman-watching-into-rounded-frame-isolated-on-white-3d-vector-illustration.jpg?s=612x612&w=0&k=20&c=x9lmmoKVqxRro-G3S48IWIKQiykb2Yv1CkuiizDJ6gw=',
      'followers': 1800,
      'quizzes': 53,
      'isFollowing': false,
    },
    {
      'id': '8',
      'name': 'Edgar Torrey',
      'username': 'edgar_torrey',
      'profileImageUrl': 'https://icon0.com/free/static2/preview2/stock-photo-avatar-man-people-icon-character-32593.jpg',
      'followers': 1800,
      'quizzes': 53,
      'isFollowing': false,
    },
  ];